-- 查询锁住的对象
-- 1
SELECT L.SESSION_ID SID, S.SERIAL#, L.LOCKED_MODE,L.ORACLE_USERNAME,
L.OS_USER_NAME,S.MACHINE, S.TERMINAL, O.OBJECT_NAME, S.LOGON_TIME
FROM V$LOCKED_OBJECT L, ALL_OBJECTS O, V$SESSION S
WHERE L.OBJECT_ID = O.OBJECT_ID
AND L.SESSION_ID = S.SID
ORDER BY SID, S.SERIAL# ;

-- 2
SELECT L.SESSION_ID SID, S.SERIAL#, L.LOCKED_MODE, L.ORACLE_USERNAME, S.USER#,
L.OS_USER_NAME,S.MACHINE, S.TERMINAL,A.SQL_TEXT, A.ACTION
FROM V$SQLAREA A,V$SESSION S, V$LOCKED_OBJECT L
WHERE L.SESSION_ID = S.SID
AND S.PREV_SQL_ADDR = A.ADDRESS
ORDER BY SID, S.SERIAL#;

-- 3
SELECT S.SID, S.SERIAL#, S.USERNAME, S.SCHEMANAME, S.OSUSER, S.PROCESS, S.MACHINE,
S.TERMINAL, S.LOGON_TIME, L.TYPE
FROM V$SESSION S, V$LOCK L
WHERE S.SID = L.SID
AND S.USERNAME IS NOT NULL
ORDER BY SID;

-- KILL锁住的进程
-- ALTER SYSTEM KILL SESSION'SID,SERIAL#';
ALTER SYSTEM KILL SESSION'34,74';


-- 查询出被锁对象，并提供 kill 脚本
SELECT S.SID, S.MACHINE, O.OBJECT_NAME, L.ORACLE_USERNAME, L.LOCKED_MODE, S.OSUSESR,
  'ALTER SYSTEM KILL SESSION '''|| S.SID || ', '|| S.SERIAL#||''';' AS KILL_COMMAND
  FROM V$LOCKED_OBJECT L, V$SESSION S, ALL_OBJECTS O
  WHERE L.SESSION_ID=S.SID AND L.OBJECT_ID=O.OBJECT_ID
  
----kill 时报错：ORA-00031 标记要删去的会话
SELECT P.SPID, S.SID, S.SERIAL#, S.USERNAME
FROM V$PROCESS P, V$SESSION S
WHERE P.ADDR=S.PADDR AND S.STATUS='KILLED';

SELECT P.SPID, S.OSUSER, S.PROGRAM
FROM V#SESSION S, V$PROCESS P
WHERE S.PADDR=P.ADDR AND S.SID=$SID;

-- OS KILL
-- UNIX
KILL -9 $SPID

-- WINDOWS
ORAKILL 实例名 $SPID